### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by harnoorsaini** [mrusme/zeit#27]
Hi, me again! 
After using zeit for a few months, I would like to compute some more statistics based on my weekly times, e.g., how much overtime I have.
I don't think zeit should do this, rather it would be nice to have a simple CSV output. Then the user can do with it as he or she pleases.
Thanks!

**Comment by mrusme** [comment]
We can add a native `csv` value to the `export` command's `--format` flag, however, since it already does JSON pretty good, you could simply do this:

```sh
zeit export | jq -r '(.[0] | keys_unsorted) as $keys | $keys, map([.[ $keys[] ]])[] | @csv'
```

Maybe you can try the command and see if that's what you're looking for? If so: You're welcome. :-) If not, please point out what you'd be missing from it!

**Comment by harnoorsaini** [comment]
Thanks! I will give it a go and get back to you. But I think it should do the trick :)
