### ISSUE TITLE
Renaming tasks/projects?

### ISSUE THREAD

**Issue by selfire1** [mrusme/zeit#28]
Hi! Thank you for this great tool. I love how simple yet powerful Zeit is.

As I've been using it more and more, I got a better grasp of how to use projects and tasks. My previous setup is a bit messy and I'l like to refactor the task and project names and associations. I tried opening `zeit.db` in a text editor and just search and replaced all instances of a project name to a new one. However, that broke the database.

Is there a way to bulk rename or is manually updating each entry the way to go?

Thanks again for your hard work on Zeit!

**Comment by mrusme** [comment]
Hey there, glad you enjoy Zeit. See, that's the beauty of the CLI, you don't necessarily need the tool to support features like bulk updates since you can easily perform those on your own, e.g.:

```sh
zeit --no-colors list -p Kenya | cut -d ' ' -f1 | xargs -I {} echo zeit entry -p Nairobi {}
```

Replace `Kenya` with the old project name and `Nairobi` with the new one. Run it and check if what it would do looks alright. If so, backup your `zeit.db` nevertheless, remove the `echo`, run it and Bob's your uncle.

Hope this helps! Feel free to reopen if further issues come up.
